baseURL: "https://nchristopher.me/"
title: Nicholas Christopher
theme: hugo-PaperMod
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    # minifyOutput: true

copyright: "&copy; 2021 Nicholas Christopher • [Source](https://github.com/nickhasoccured/nchristopher.me)"

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "I make open-source software for the internet."
    author: Nicholas Christopher
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowToc: true
    comments: false
    images: ["img/og-banner.png"]

    homeInfoParams:
        Title: "👋 Hello, I'm Nick"
        Content: >
            I make open-source software for the internet. My projects aim to be useful to me or (*hopefully*) useful to others. I'm currently using web-based languages, but I'm looking to branch out in the future!

    socialIcons:
        - name: Twitter
          url: "https://twitter.com/nickhasoccured"
        - name: GitHub
          url: "https://github.com/nickhasoccured"
        - name: email
          url: "mailto:nchristopher@tuta.io"
        - name: Reddit
          url: "https://reddit.com/u/nickhasoccured"
        - name: KoFi
          url: "https://ko-fi.com/nchristopher"
        - name: Twitch
          url: "https://twitch.tv/nickhasoccured"
        - name: RsS
          url: "index.xml"

    label:
        text: "Home"
        #icon: <path>
        iconHeight: 32

    assets:
        favicon: "icon/favicon.ico"
        favicon16x16: "icon/favicon-16x16.png"
        favicon32x32: "icon/favicon-32x32.png"
        apple_touch_icon: "icon/apple-touch-icon.png"
        # safari_pinned_tab: <path>

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

menu:
    main:
        - identifier: about
          name: About
          url: /about/
          weight: 1
        # - identifier: tags
        #   name: Tags
        #   url: /tags/
        #   weight: 2
        - identifier: archive
          name: Archive
          url: /archive/
          weight: 3
        - identifier: search
          name: Search
          url: /search/
          weight: 4

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
